#!/bin/bash
if [ "$1" = "build" ]; then
    export COMPOSE_FILE=docker-compose.yaml:../backend/docker-compose.yaml:../backend/docker-compose.build.yaml
else
    export COMPOSE_FILE=docker-compose.yaml:docker-compose.dev.yaml:../backend/docker-compose.yaml:../backend/docker-compose.dev.yaml
fi

export BACKEND_ROOT=../backend
export FRONTEND_ROOT=.

export COMPOSE_PROJECT_NAME=fntch
export IMAGE_TAG=$(git rev-parse --abbrev-ref HEAD)

export DOCKER_REGISTRY=docker.mel.fm/fntch
export FNTCH_ENV=dev
export BACKEND_BIND=4000

export FRONTEND_BIND=3000
export FRONTEND_STATIC_BIND=3001

export PG_BIND=127.0.0.1:55432
export PG_DATA_DIR=~/docker-pg-fntch
export POSTGRES_PASSWORD=123qwe
export POSTGRES_USER=fntch